version: '3'
services:
  cg-mobile-nginx:
    container_name: "cg-mobile-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - cg-mobile-app
    ports:
      - 80:80
    volumes:
      - ./:/src

  cg-mobile-app:
    container_name: "cg-mobile-app"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - cg-mobile-mysql
    ports:
      - 5173:5173
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  cg-mobile-mysql:
    image: mysql:8.0.37
    command: --max_allowed_packet=32505856
    container_name: "cg-mobile-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cg-mobile
    ports:
      - 3306:3306

  cg-mobile-redis:
    image: redis:alpine
    container_name: "cg-mobile-redis"
    ports:
      - 16379:6379
